CREATE OR REPLACE FUNCTION distance(
    x1 DOUBLE PRECISION,
    x2 DOUBLE PRECISION,
    y1 DOUBLE PRECISION,
    y2 DOUBLE PRECISION
)
RETURNS DOUBLE PRECISION AS $$
BEGIN
    RETURN SQRT(POWER(x2-x1, 2) + POWER(y2-y1, 2));
END
$$ LANGUAGE plpgsql;

SELECT
    ROUND(SUM(distance(c1.x, c2.x, c1.y, c2.y))::NUMERIC, 9)::DOUBLE PRECISION AS total
FROM cities AS c1
LEFT JOIN cities AS c2 ON c1.id+1 = c2.id;